# Identificacion del proyecto en SonarQube local.
sonar.projectKey=parra-post2-u10
sonar.projectName=Productos Service
sonar.projectVersion=1.0

# Estructura Maven estandar usada por el laboratorio.
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Integracion de cobertura JaCoCo generada con mvn clean verify.
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Codificacion del codigo fuente.
sonar.sourceEncoding=UTF-8
